repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Backend hooks
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        files: ^backend/.*\.py$

  # Docker hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
        files: ^backend/Dockerfile

  # JavaScript / frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|html|css|mjs)$
